module.exports = {

// He's a man of wealth and taste, you know.
  hereIAm : '\n\"Good morning, my dear Stepan Bogdanovich!\"\n\nStuttering, you ask the mysterious man what he wants while he checks his pocket watch.\n\nSmiling, he replies:\"Eleven. I have been waiting exactly an hour for you to wake up. Our appointment was at ten!\"\n\nYou feel suddenly underdressed and clumsily start to put on your trousers, having spotted them on the chair by the bed. Appointment? You\'ve only just met this man.\n\n\"Have you forgotten my name?\" asks the man. \"No matter. Come over to the TABLE. Something sharp and peppery to eat - and a little hair of the dog - will bring you back to life.\"\n',

  strangerIntroScene : '\nYou call out for your maid, Grunya. Upon hearing no response, you shout for your flatmate, Berlioz. Still nothing. Won\'t anybody bring you an aspirin? Eventually you haul yourself up and go to look in the mirror.\n\nYour appearance is scruffy, and you are wearing a shirt, tie, underpants and socks. Suddenly you realise that you are not the only person you can see in the mirror. Reflected in its surface, standing behind you, is a STRANGER. You feel certain that you\'ve never met him before.\n\nIs it a good idea to TALK to strangers?\n',

// If you drank the vodka:
  brunch1 : '\nYour headache recedes but your memory has not improved. You\'re still unclear as to who this man is. Your confusion must show on your face, and the stranger says gravely:\n\n\"Woland, professor of black magic. I offered myself as a guest artiste at the Variety, which you accepted - and signed a contract for seven perfomances.\"\n\nYou gasp audibly, but Woland continues.\"You invited me here at ten o\'clock to conclude the details, but when I arrived your maid told me what a state you were in, so I sent her for some vodka and food. No, no, put your wallet away, Stepan, what nonsense!\"\n\nYou take a few moments to take this new information in. It does at least explain Woland\'s presence in your room, as well as the food. One thing is still bothering you, though.\n\n\"Would you mind showing me the contract, Woland?\"\n\n\"Oh, but of course\", he says. \"I shall put it on the table. TAKE it and LOOK at it.\"\n',

// If you have not yet had any vodka:
  brunch2 : '\nYou ask the stranger if he intends to dine with you.\n\n\"I never eat when I\'m drinking\", he says, and pours out two glasses of vodka from the decanter.\"Have you remembered my name yet?\"\n\nYou can only grin sheepishly and shrug your shoulders. Some dim memories, including attempting to kiss a woman who worked for the radio, and going to the dacha, have returned to you, but they seem uninteresting in comparison to the situation you\'re currently in.\n\nThe stranger pushes a glass towards you. \"Better DRINK some VODKA, Stepan, then we can continue our TALK.\"\n',

  contract : '\nA contract for Woland to perform at the Variety Theatre, of which you are the manager. It bears both your signature and that of the treasurer, Rimsky, and further reading indicates that Woland has been paid a cash advance of ten thousand roubles against his fee of thirty-five thousand roubles.\n\nWhat the hell? There\'s no way that you could forget a deal of this magnitude, but any further signs of disbelief would surely offend.\n\nDoing your best to ignore a rising sense of panic, you resolve to GO to the HALLWAY to see if you can find Grunya, and possibly place a phonecall to Rimsky about this contract.\n',

  hallSetup : '\nYou excuse yourself and head to the hallway. There\'s a TELEPHONE here that you can USE to call Rimsky about the contract. To one side is the door to Berlioz\'s room, but there appears to be a seal over it that you don\'t recall seeing before. To the other side is a mirror.\n',

// It's set in 1930s Moscow.
  politicalConcerns : '\nThe door to Berlioz\'s room. It has a vast wax seal on it now, and panic grips you as you recall a potentially compromising conversation you had with him some days before. It was hardly that objectionable, but seeing the seal makes you wonder if it had somehow been heard. Your mind then races to a politically sensitive article that you had pushed Berlioz to publish in his magazine - could that be the cause of his apparent disappearance?\n',

  rimskyCall : '\nYou dial Rimsky, the treasurer of the Variety Theatre. As you wait for him to pick up, you note that you must be delicate about this, as you\'re sure to sound odd if you bluntly ask if you signed a thirty-five thousand rouble contract yesterday.\n\n"Yes?" comes Rimsky\'s harsh, unpleasant voice.\n\n"Hello," you say gently. "Likhodeyev speaking. It\'s about this... er... artiste. In my flat. Called Woland. I just wanted to ask... is everything okay?"\n\n\"Oh, the black magician?\" says Rimsky. \"The posters will be here any minute now.\"\n\nYou mumble some sort of assent and replace the receiver. What a ridiculous thing to have forgotten. You begin to wonder if Grunya the maid is actually in - maybe you should GO to the KITCHEN and look for her.\n',

  bedroomAgainSetup : '\nYou knock on the kitchen door and shout out for Grunya. To your surprise, it\'s not Grunya who replies, but Woland. From the bedroom, he says loudly: \"Grunya isn\'t here. I sent her away to her family in Voronezh. She complained that you had cheated her out of her leave.\"\n\nYou find this so unexpected and absurd that you turn to head back to the bedroom, but as you do, you see an apparition in the mirror of a tall, thin man wearing a pince-nez. As you try to inspect him, he vanishes, and is replaced in the mirror with the spectre of a huge black cat. You cry out and run to the bedroom.\n\nWoland is no longer alone. The tall man and the vast cat from the mirror are now here too. Although you\'re terrified, maybe you ought to TALK to them.\n',

// Did you take the frankfurters?
  yesIDid : '\nThe cat looks over the table, but seemingly sees nothing to its liking. \"Hello Stepan,\" it says, then grumbles, gesturing at the table. \"I thought there would at least be some meat here.\"\n',

  noIDidNot : '\nThe cat is piling frankfurters onto a plate. \"Hello Stepan,\" it says. \"Lovely flat. Don\'t mind me, though. I\'m famished.\"\n',

  wolandIntroducesHisAssistants : '\n\"You seem astonished, Stepan Bogdanovich! But I assure you that you should not be. The CAT is mine and this tall fellow is my ASSISTANT.\"\n\nFrom your bedroom mirror steps yet another intruder: a broad-shouldered man with fiery red hair. Faint with fear, you lean back against the wall. Woland greets the newcomer. "Ah, AZAZELLO!\"\n',

  tallManSpeaks : '\n\"That\'s them!\" cries the tall man in a goatish voice, referring to you in the plural for some reason. \"They\'ve been behaving disgustingly lately. Getting drunk, carrying on with women, trading on their position and not doing a stroke of work - not that they could do anything even if they tried because they\'re completely incompetent. Pulling the wool over the boss\'s eyes, that\'s what they\'ve been doing!\"\n\nOuch. Okay. You can feel yourself sweating at these accusations, though you cannot tell how this stranger would know any of this.\n',

  azazelloSpeaks : '\nThe man called Azazello glances at you briefly in a derogatory sort of way, then turns to the cat. \"I cannot fathom how this man ever came to manage a theatre,\" he says in a nasal voice. \"He\'s as much a manager as I am a bishop.\"\n\n\"You don\'t look much like a bishop, Azazello,\" says the cat.\n\n\"That\'s what I mean,\" Azazello snarls in response before addressing Woland. \"Will you permit us, messire, to kick him out of Moscow?\"\n\nThe cat hisses, and the assembled company begin to advance upon you.\n\nYou feel strongly that now would be a very good time to GO back to the HALLWAY, and do your best to get away from these unnatural interlopers.',

  hallAgainSetup : '\nThere\'s still a telephone and a mirror here, and seal over Berlioz\'s room remains undisturbed. You can get to the KITCHEN or the front DOOR.\n',

  kitchenSetup : '\nThe kitchen of your flat. This is usually Grunya\'s domain, but she definitely isn\'t here. You\'re not sure if you can believe that Woland sent her to Voronezh, but it would hardly be the oddest thing that\'s happened today. There\'s a stove, pans and cupboards here - it\'s not an unusual kitchen by any means. Anyway, you would surely be better served by returning to the HALLWAY and getting out of here before Woland and his associates catch up with you.\n',

  yaltaSetup : '\nYou open the door, ready to run. However, in front of you stands Woland, with his associates behind him. Paralysed by fear, you begin to feel extremely dizzy and lightheaded.\n\n\"My assistants will be needing somewhere to stay, Stepan,\" says Woland. \"And so it seems that there is one too many of us in this flat. And that one, I rather think, is you.\"\n\nThe world spins as you drop to the floor, although you notice the sharp pain as your head hits the doorframe on your way down. Detached from yourself, you wonder if you\'re dying.\n\nBut you don\'t die. The next thing you\'re aware of is a blue sky above you and the sound of waves. You\'re lying on what seems to be stone. When you\'re ready, you should take a LOOK around.',

  yaltaPartTwo : '\nPlaceholder\n'
}
