module.exports = {

  // He's a man of wealth and taste, you know.
  hereIAm: '\n\"Good morning, my dear Stepan Bogdanovich!\"\n\nStuttering, you ask the mysterious man what he wants while he checks his pocket watch.\n\nSmiling, he replies:\"Eleven. I have been waiting exactly an hour for you to wake up. Our appointment was at ten!\"\n\nYou feel suddenly underdressed and clumsily start to put on your trousers, having spotted them on the chair by the bed. Appointment? You\'ve only just met this man.\n\n\"Have you forgotten my name?\" asks the man. \"No matter. Come over to the TABLE. Something sharp and peppery to eat - and a little hair of the dog - will bring you back to life.\"\n',

  strangerIntroScene: '\nYou call out for your maid, Grunya. Upon hearing no response, you shout for your flatmate, Berlioz. Still nothing. Won\'t anybody bring you an aspirin? Eventually you haul yourself up and go to look in the mirror.\n\nYour appearance is scruffy, and you are wearing a shirt, tie, underpants and socks. Suddenly you realise that you are not the only person you can see in the mirror. Reflected in its surface, standing behind you, is a STRANGER. You feel certain that you\'ve never met him before.\n\nIs it a good idea to TALK to strangers?\n',

  brunch1: '\nYour headache recedes but your memory has not improved. You\'re still unclear as to who this man is. Your confusion must show on your face, and the stranger says gravely:\n\n\"Woland, professor of black magic. I offered myself as a guest artiste at the Variety, which you accepted - and signed a contract for seven perfomances.\"\n\nYou gasp audibly, but Woland continues.\"You invited me here at ten o\'clock to conclude the details, but when I arrived your maid told me what a state you were in, so I sent her for some vodka and food. No, no, put your wallet away, Stepan, what nonsense!\"\n\nYou take a few moments to take this new information in. It does at least explain Woland\'s presence in your room, as well as the food. One thing is still bothering you, though.\n\n\"Would you mind showing me the contract, Woland?\"\n\n\"Oh, but of course\", he says. \"I shall put it on the table. TAKE it and LOOK at it.\"\n',

  brunch2: '\nYou ask the stranger if he intends to dine with you.\n\n\"I never eat when I\'m drinking\", he says, and pours out two glasses of vodka from the decanter.\"Have you remembered my name yet?\"\n\nYou can only grin sheepishly and shrug your shoulders. Some dim memories, including attempting to kiss a woman who worked for the radio, and going to the dacha, have returned to you, but they seem uninteresting in comparison to the situation you\'re currently in.\n\nThe stranger pushes a glass towards you. \"Better DRINK some VODKA, Stepan, then we can continue our TALK.\"\n',

  contract: '\nA contract for Woland to perform at the Variety Theatre, of which you are the manager. It bears both your signature and that of the treasurer, Rimsky, and further reading indicates that Woland has been paid a cash advance of ten thousand roubles against his fee of thirty-five thousand roubles.\n\nWhat the hell? There\'s no way that you could forget a deal of this magnitude, but any further signs of disbelief would surely offend.\n\nDoing your best to ignore a rising sense of panic, you resolve to GO to the HALLWAY to see if you can find Grunya, and possibly place a phonecall to Rimsky about this contract.\n',

  hallSetup: '\nYou excuse yourself and head to the hallway. There\'s a TELEPHONE here that you can USE to call Rimsky about the contract. To one side is the door to Berlioz\'s room, but there appears to be a seal over it that you don\'t recall seeing before. To the other side is a mirror.\n'
}
